<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Allsiswa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_logged_in();
        $this->load->model('Pelanggaran_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $this->db->where("username", $this->session->userdata('username'));
        $this->db->where("kelas", $this->session->userdata('id_kelas'));
        $pelanggaran = $this->db->get('tbl_pelanggaran')->result();

        $data = array(
            'pelanggaran_data' => $pelanggaran,
            'start' => 1

        );
        $data['title'] = 'Pelanggaran';
        $data['user'] = $this->db->get_where('tbl_user', ['username' => $this->session->userdata('username')])->row_array();

        $this->load->view('templates/header', $data);
        $this->load->view('templates/sidebar', $data);
        $this->load->view('templates/topbar', $data);
        $this->load->view('all_siswa/tbl_pelanggaran_list_siswa', $data);
        $this->load->view('templates/footer', $data);
    }

    public function read($id)
    {
        $row = $this->Pelanggaran_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'username' => $row->username,
                'pelanggaran' => $row->pelanggaran,
                'sanksi' => $row->sanksi,
                'kelas' => $row->kelas,
                'tgl' => $row->tgl,
            );
            $data['title'] = 'Pelanggaran';
            $data['user'] = $this->db->get_where('tbl_user', ['username' => $this->session->userdata('username')])->row_array();

            $this->load->view('templates/header', $data);
            $this->load->view('templates/sidebar', $data);
            $this->load->view('templates/topbar', $data);
            $this->load->view('all_siswa/tbl_pelanggaran_read_siswa', $data);
            $this->load->view('templates/footer', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pelanggaran'));
        }
    }
}

/* End of file Pelanggaran.php */
/* Location: ./application/controllers/Pelanggaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-28 09:45:48 */
/* http://harviacode.com */