<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lap_pelanggaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_logged_in();
        $this->load->model('Pelanggaran_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $pelanggaran = "";
        $level = $this->session->userdata('id_user_level');
        if ($level == 9) {
            $this->db->where("kelas", $this->session->userdata('id_kelas'));
            $pelanggaran = $this->db->get('tbl_pelanggaran')->result();
        } elseif ($level == 12) {
            $this->db->order_by("kelas", "ASC");
            $pelanggaran = $this->db->get('tbl_pelanggaran')->result();
        } else {
            $this->db->where("username", $this->session->userdata('id_kelas'));
            $pelanggaran = $this->db->get('tbl_pelanggaran')->result();
        }

        $data = array(
            'pelanggaran_data' => $pelanggaran,
            'start' => 1

        );
        $data['title'] = 'Pelanggaran';
        $data['user'] = $this->db->get_where('tbl_user', ['username' => $this->session->userdata('username')])->row_array();

        $this->load->view('templates/header', $data);
        $this->load->view('templates/sidebar', $data);
        $this->load->view('templates/topbar', $data);
        $this->load->view('all_ortu/tbl_pelanggaran_list_ortu', $data);
        $this->load->view('templates/footer', $data);
    }
    public function read($id)
    {
        $row = $this->Pelanggaran_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'username' => $row->username,
                'pelanggaran' => $row->pelanggaran,
                'sanksi' => $row->sanksi,
                'kelas' => $row->kelas,
                'tgl' => $row->tgl,
            );
            $data['title'] = 'Pelanggaran';
            $data['user'] = $this->db->get_where('tbl_user', ['username' => $this->session->userdata('username')])->row_array();

            $this->load->view('templates/header', $data);
            $this->load->view('templates/sidebar', $data);
            $this->load->view('templates/topbar', $data);
            $this->load->view('all_ortu/tbl_pelanggaran_read_ortu', $data);
            $this->load->view('templates/footer', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pelanggaran'));
        }
    }

    public function cetak()
    {
        // Create an instance of the class:
        $mpdf = new \Mpdf\Mpdf();
        $dari = $this->input->post('dari');
        $sampai = $this->input->post('sampai');
        $result = "";
        if ($dari == "" or $sampai == "") {
            $result = $this->db->query("SELECT * FROM tbl_pelanggaran")->result();
        } else {
            $result = $this->db->query("SELECT * FROM tbl_pelanggaran WHERE tgl BETWEEN '$dari' AND '$sampai'")->result();
        }

        $data = [
            "data_materi" => $result,
            "title" => "LAPORAN PELANGGARAN SISWA",
        ];
        $html = $this->load->view('cetak/cetak_pelanggaran', $data, true);
        $mpdf->WriteHTML($html);
        $mpdf->Output();
    }

    public function print($id = null)
    {
        // Create an instance of the class:
        $mpdf = new \Mpdf\Mpdf();
        $dari = $this->input->post('dari');
        $sampai = $this->input->post('sampai');
        $result = "";
        if ($dari == "" or $sampai == "") {
            $result = $this->db->query("SELECT * FROM tbl_pelanggaran WHERE username='$id'")->result();
        } else {
            $result = $this->db->query("SELECT * FROM tbl_pelanggaran WHERE tgl BETWEEN '$dari' AND '$sampai' AND username='$id'")->result();
        }

        $data = [
            "data_materi" => $result,
            "title" => "LAPORAN PELANGGARAN SISWA",
        ];
        $html = $this->load->view('cetak/cetak_pelanggaran', $data, true);
        $mpdf->WriteHTML($html);
        $mpdf->Output();
    }
}

/* End of file Pelanggaran.php */
/* Location: ./application/controllers/Pelanggaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-28 09:45:48 */
/* http://harviacode.com */